Evaluate complex expressions
avast/yls pull request #16
Opened 2022-09-11 20:19 UTC by tomaskender

Support complex expression extraction and evaluation. You can either hover or select an expression.

If you hover it, YLS will guess the boundaries of expression and pass it to evaluator. So, if you hover `==`, `op1 == op2` gets passed to the evaluator. If you hover `op1`, `op1` gets passed to evaluator.

If you select an expression, YLS will again try to auto-adjust the selection and pass the entire expression. Even if you select only `p ==`, `op1 == op2` is evaluated.

2022-09-15 17:49 UTC, MatejKastak requested changes

2022-09-15 17:49 UTC, MatejKastak commented on yls/utils.py
> +    def _extract(curr_rule: yaramod.Rule, extracted_rules: List[str]) -> List[str]:
Nitpick: Use new style of typehints for consistency
```suggestion
    def _extract(curr_rule: yaramod.Rule, extracted_rules: list[str]) -> list[str]:
```

2022-09-19 22:46 UTC, tomaskender commented on yls/utils.py
> +            if identifier and identifier == identifier.upper()
fixed: moved away from manual identifier detection to observer-based

2022-09-20 10:03 UTC, MatejKastak approved these changes
LGTM :+1:

2022-09-20 10:04 UTC, merged